version: '3.9'
services:
  backend:
      build:
        context: .
        dockerfile: Dockerfile.backend
      ports:
        - "5003:5003" 
      volumes:
        - .:/app
  frontend:
      build:
        context: .
        dockerfile: Dockerfile.frontend
      ports:
        - "3000:3000"
      volumes:
        - .:/app
      command: nginx -g 'daemon off;'
  